// Generated by https://quicktype.io
class TrailerDao {
  String id;
  String iso6391;
  String iso31661;
  String key;
  String name;
  String site;
  int size;
  String type;

  factory TrailerDao.fromJSON(Map<String, dynamic> map) {
    return TrailerDao(
      id: map['id'],
      iso6391: map['iso_6391'],
      iso31661: map['iso_31661'],
      key: map['key'],
      name: map['name'],
      site: map['site'],
      size: map['size'],
      type: map['type'],
    );
  }

  TrailerDao({
    this.id,
    this.iso6391,
    this.iso31661,
    this.key,
    this.name,
    this.site,
    this.size,
    this.type,
  });
}
